version: '3.9'

services:
  goauth:
    container_name: goauth
    image: goauth:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: goauth
    ports:
      - 8080:8080
    networks:
      - goauth_network
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - env/.goauth.env

  mysqldb:
    image: mysql
    container_name: goauth_db
    env_file:
      - env/.goauth.env
    volumes:
      - goauth_db:/var/lib/mysql
      - ./cfg/db_setup.sql/:/docker-entrypoint-initdb.d/init.sql
    networks:
      - goauth_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  goauth_db:
    name: goauth


networks:
  goauth_network:
    driver: bridge
    name: goauth
